### ISSUE TITLE
PebbleColor typo

### ISSUE THREAD

**Issue by ptruongnet** [fletchto99/PHPebbleTimeline#6]
PebbleColor class in PinLayout.php is named "PebbleColour" - documentation references the former.

**Comment by fletchto99** [comment]
Ah shoot. That's the problem with being Canadian, spelling is always slightly different. I though I corrected Colour to Color everywhere. Turns out I forgot to do that in the actual library. Thanks for pointing this out!

I'll think about how I'm going to proceed as a few apps already use this library and changing PebbleColour to PebbleColor will break them. That being said the docs can't differ from the actual library.

**Comment by ptruongnet** [comment]
Yeah, it may be useful to at least point it out in the documentation at least.

Debugging and making the necessary change to the class name was not difficult - it's in one place only. Once that is done, everything else works as described.

**Comment by fletchto99** [comment]
Yeah for now I will update the documentation to reflect the code, then in a future major release when/if I rewrite the API I will adjust accordingly.

**Comment by ptruongnet** [comment]
Sounds good! Thanks for creating this btw, it was very simple to use and got me started easily on the API.

**Comment by fletchto99** [comment]
For now I have corrected the docs. Eventually it will use Color, to be consistent with Pebble's SDKs
